package com.dms.mapper;

import com.dms.dto.request.DocumentUpdateRequest;
import com.dms.dto.request.DocumentUploadRequest;
import com.dms.dto.response.DocumentResponse;
import com.dms.entity.Document;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.mapstruct.ReportingPolicy;

import java.util.List;

@Mapper(
    componentModel = "spring",
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
    unmappedTargetPolicy = ReportingPolicy.IGNORE,
    uses = {DepartmentMapper.class, DocumentCategoryMapper.class, UserMapper.class, DocumentVersionMapper.class}
)
public interface DocumentMapper {

    // ─── Entity → Response ────────────────────────────────────────────────────

    @Mapping(target = "department", source = "department", qualifiedByName = "departmentToResponse")
    @Mapping(target = "category",   source = "category")
    @Mapping(target = "owner",      source = "owner")
    @Mapping(target = "versions",   source = "versions")
    DocumentResponse toResponse(Document document);

    List<DocumentResponse> toResponseList(List<Document> documents);

    // ─── UploadRequest → Entity (file/derived fields set by service) ──────────

    @Mapping(target = "id",             ignore = true)
    @Mapping(target = "documentNumber", ignore = true)   // generated by service
    @Mapping(target = "currentVersion", constant = "1")
    @Mapping(target = "status",         constant = "DRAFT")
    @Mapping(target = "filePath",       ignore = true)   // set after storage
    @Mapping(target = "fileName",       ignore = true)   // set after storage
    @Mapping(target = "fileSize",       ignore = true)   // set after storage
    @Mapping(target = "mimeType",       ignore = true)   // set after storage
    @Mapping(target = "isArchived",     constant = "false")
    @Mapping(target = "archivedAt",     ignore = true)
    @Mapping(target = "createdAt",      ignore = true)
    @Mapping(target = "updatedAt",      ignore = true)
    @Mapping(target = "createdBy",      ignore = true)
    @Mapping(target = "updatedBy",      ignore = true)
    @Mapping(target = "department",     ignore = true)   // resolved by service
    @Mapping(target = "category",       ignore = true)   // resolved by service
    @Mapping(target = "owner",          ignore = true)   // set to current user
    @Mapping(target = "versions",       ignore = true)
    @Mapping(target = "isActive",       ignore = true)
    Document toEntity(DocumentUploadRequest request);

    // ─── UpdateRequest → Entity (patch semantics) ─────────────────────────────

    @Mapping(target = "id",             ignore = true)
    @Mapping(target = "documentNumber", ignore = true)
    @Mapping(target = "currentVersion", ignore = true)
    @Mapping(target = "status",         ignore = true)
    @Mapping(target = "filePath",       ignore = true)
    @Mapping(target = "fileName",       ignore = true)
    @Mapping(target = "fileSize",       ignore = true)
    @Mapping(target = "mimeType",       ignore = true)
    @Mapping(target = "isArchived",     ignore = true)
    @Mapping(target = "archivedAt",     ignore = true)
    @Mapping(target = "createdAt",      ignore = true)
    @Mapping(target = "updatedAt",      ignore = true)
    @Mapping(target = "createdBy",      ignore = true)
    @Mapping(target = "updatedBy",      ignore = true)
    @Mapping(target = "department",     ignore = true)
    @Mapping(target = "category",       ignore = true)
    @Mapping(target = "owner",          ignore = true)
    @Mapping(target = "versions",       ignore = true)
    @Mapping(target = "isActive",       ignore = true)
    void updateEntityFromRequest(DocumentUpdateRequest request, @MappingTarget Document document);
}